name: Changesets

on:
  workflow_call:
    inputs:
      repository:
        description: target repository
        required: true
        type: string
    secrets:
      npm_token:
        description: npm token for use
        required: true


permissions:
  contents: write
  pull-requests: write
  packages: write

jobs:
  lint:
    uses: coldsurfers/workflows/.github/workflows/lint-ci.yml@main
    secrets:
      npm_token: ${{ secrets.npm_token }}
  changesets:
    if: ${{ github.repository == inputs.repository }}

    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup
        uses: coldsurfers/workflows/.github/actions/setup@main
        with:
          NPM_TOKEN: ${{ secrets.npm_token }}

      - name: Create Release Pull Request or Publish to npm
        uses: changesets/action@v1
        with:
          title: 'chore: version packages'
          commit: 'chore: version packages'
          version: pnpm changeset version
          publish: pnpm changeset publish
          createGithubReleases: true     # 릴리즈 생성 활성화
        env:
          GITHUB_TOKEN: ${{ secrets.npm_token }}
          NPM_TOKEN: ${{ secrets.npm_token }}
