name: Lint
on:
  workflow_call:
    secrets:
      npm_token:
        description: npm token for use
        required: true

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup
        uses: coldsurfers/workflows/.github/actions/setup@main
        with:
          NPM_TOKEN: ${{ secrets.npm_token }}

      - name: Lint files
        run: pnpm turbo run lint

      - name: Typecheck files
        run: pnpm turbo check:type
